
backend:

  name: github
  repo: MarioWindsor/bamnio-website
  branch: main

local_backend: true

media_folder: "/media/uploads"
public_folder: "/media/uploads"

collections:
  - name: "services"
    label: "Services"
    folder: "services"
    icon: storefront
    create: true
    slug: "{{name}}"
    editor:
      preview: false
    sortable_fields: ['date', 'name']
    fields:
      - { label: "Tags", name: "tags", widget: "hidden", default: ["projects"] }
      - { label: "Created Date", name: "date", widget: "datetime", default: "{{now}}" }
      - { label: "Project Name", name: "name", widget: "string" }
  - name: "articles"
    label: "Articles"
    folder: "articles"
    icon: newsmode
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    sortable_fields: ['date', 'title']
    fields:
      - { label: "Tags", name: "tags", widget: "hidden", default: ["articles"] }
      - { label: "Created Date", name: "date", widget: "datetime", default: "{{now}}" }
      - { label: "Title", name: "title", widget: "string", hint: "Limit to 45 Characters" }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Cover Image", name: "cover", widget: "image", hint: "Aspect Ratio 2:1 (Width = 2 x Height)", required: false }
      - { label: "SEO Short Description", name: "description", widget: "text", hint: "Limit to 150 Characters", required: false }
      - label: "Author Credit"
        name: "author-credit"
        widget: "object"
        collapsed: true
        required: false
        fields:
          - { label: "Author Name", name: "name", widget: "string", hint: "Eg: Hima Nair", required: false }
          - { label: "Author Title", name: "title", widget: "string", hint: "Eg: Speech Language Pathologist", required: false }
          - { label: "Author Website URL (Optional)", name: "website", hint: "Eg: `https://bambinotherapy.com` — Note: Add Full URL including https", widget: "string", required: false }
          - { label: "Article Source Backlink (Optional)", name: "backlink", widget: "string", hint: "Eg: `https://bambinotherapy.com/articles/sample-article`", required: false }
          - { label: "Author Photo", name: "photo", widget: "image", hint: "Aspect Ratio 1:1 (Square Image)", required: false }
  - name: "testimonials"
    label: "Testimonials"
    folder: "testimonials"
    icon: reviews
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    sortable_fields: ['date', 'title']
    fields:
      - { label: "Tags", name: "tags", widget: "hidden", default: ["testimonials"] }
      - { label: "Created Date", name: "date", widget: "datetime", default: "{{now}}" }
      - { label: "Person Name", name: "title", widget: "string" }
      - { label: "Rating", name: "rating", widget: "number", min: 0, max: 5, value_type: "int" }
      - { label: "Review", name: "review", widget: "text" }
  - name: "settings"
    label: "Settings"
    icon: settings
    editor:
      preview: false
    files:
      - name: "menu"
        label: "Menu"
        file: "_data/menu.json"
        fields:
          - label: "link"
            name: "link"
            widget: "list"
            summary: '{{fields.title}} → {{fields.path}}'
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Path", name: "path", widget: "string" }


