
backend:
  # name: github
  name: git-gateway
  branch: main
  repo: MarioWindsor/bambino-website

output:
  omit_empty_optional_fields: true

local_backend: true

media_folder: "/media/uploads"
public_folder: "/media/uploads"

collections:
  - name: "services"
    label: "Services"
    folder: "services"
    icon: storefront
    create: true
    slug: "{{name}}"
    editor:
      preview: false
    sortable_fields: ['date', 'name']
    fields:
      - { label: "Tags", name: "tags", widget: "hidden", default: ["projects"] }
      - { label: "Created Date", name: "date", widget: "datetime", default: "{{now}}" }
      - { label: "Project Name", name: "name", widget: "string" }
      - label: "Metadata"
        name: "metadata"
        widget: "object"
        collapsed: true
        fields:
          - { label: "Prefix Name with Vaswani", name: "prefix-name", widget: "boolean", default: true }
          - label: "Project Type"
            name: "type"
            widget: "select"
            multiple: false
            options:
              - { label: "Residential", value: "residential" }
              - { label: "Commercial", value: "commercial" }
              - { label: "Hospitality", value: "hospitality" }
            default: residential
          - { label: "Project Label", name: "project-label", widget: "string", required: false, hint: "Eg: Luxury 3 & 4 Bedroom Apartments" }
          - label: "Status"
            name: "status"
            widget: "select"
            multiple: false
            options:
              - { label: "Ongoing", value: "ongoing" }
              - { label: "Completed", value: "completed" }
            default: ongoing
          - { label: "Status Label", name: "status-label", widget: "string", required: false, hint: "Eg: Construction in Full Swing" }
          - { label: "Starting Price", name: "starting-price", widget: "string", required: false, hint: "Eg: Starting at ₹2.82Cr" }
          - { label: "Unit Size", name: "unit-size", widget: "string", required: false, hint: "Eg: 1970sqft to 2730sqft Apartments" }
          - { label: "Location Label (Area, City)", name: "location-label", widget: "string", required: false, hint: "Eg: ECC Main Road, Whitefield" }
          - { label: "RERA Number", name: "rera-number", widget: "string", required: false, hint: "Eg: PRM/KA/RERA/1251/446/PR/180424/006808" }
      - label: "Cover"
        name: "cover"
        widget: "object"
        collapsed: true
        fields:
          - { label: "Project Logo", name: "logo", widget: "image", choose_url: false, required: false }
          - { label: "Background Image", name: "background", widget: "image", choose_url: false, required: false }
          - { label: "Walkthough Video ID", name: "video", widget: "string", required: false, hint: "YouTube Video ID (Eg: 3OyRc5eczbc)" }
      - label: "Overview"
        name: "overview"
        widget: "object"
        collapsed: true
        fields:
          - { label: "Heading", name: "heading", widget: "string", required: false }
          - { label: "Sub Heading", name: "sub-heading", widget: "string", required: false }
          - { label: "Description", name: "description", widget: "text", required: false }
          - label: "Gallery"
            name: "gallery"
            widget: "list"
            required: false
            minimize_collapsed: true
            summary: '{{fields.image}} {{fields.caption}}'
            fields:
              - { label: "Image", name: "image", widget: "image", choose_url: false }
              - { label: "Caption", name: "caption", widget: "string", required: false }
      - label: "Project Film"
        name: "film"
        widget: "object"
        collapsed: true
        fields:
          - { label: "Heading", name: "heading", widget: "string", required: false }
          - { label: "Sub Heading", name: "sub-heading", widget: "string", required: false }
          - { label: "Video ID", name: "video", widget: "string", required: false, hint: "YouTube Video ID (Eg: 3OyRc5eczbc)" }
      - label: "Site Plan"
        name: "siteplan"
        widget: "object"
        collapsed: true
        fields:
          - { label: "Heading", name: "heading", widget: "string", required: false }
          - { label: "Sub Heading", name: "sub-heading", widget: "string", required: false }
          - label: "Master Plan"
            name: "masterplan"
            widget: "list"
            required: false
            minimize_collapsed: true
            summary: '{{fields.image}} {{fields.caption}}'
            fields:
              - { label: "Title", name: "title", widget: "string", }
              - { label: "Image", name: "image", widget: "image", choose_url: false }
          - label: "Floor Plan"
            name: "floorplan"
            widget: "list"
            required: false
            minimize_collapsed: true
            summary: '{{fields.title}} {{fields.image}}'
            fields:
              - { label: "Title", name: "title", widget: "string", }
              - { label: "Image", name: "image", widget: "image", choose_url: false }
      - label: "Amenities"
        name: "amenities"
        widget: "object"
        collapsed: true
        fields:
          - { label: "Heading", name: "heading", widget: "string", required: false }
          - { label: "Sub Heading", name: "sub-heading", widget: "string", required: false }
          - { label: "Description", name: "description", widget: "text", required: false }
          - { label: Cover Image, name: cover-image, widget: image, choose_url: false, required: false, hint: "Dimensions: 1200 x 400 pixels" }
          - label: "Amenity"
            name: "amenity"
            widget: "list"
            required: false
            minimize_collapsed: true
            summary: '{{fields.name}} {{fields.icon}}'
            fields:
              - {dlabel: "Name", name: "name", widget: "string", }
              - { label: "Icon", name: "icon", widget: "image", choose_url: false }
          - label: "Gallery"
            name: "gallery"
            widget: "list"
            required: false
            minimize_collapsed: true
            summary: '{{fields.image}} {{fields.caption}}'
            fields:
              - { label: "Image", name: "image", widget: "image", choose_url: false }
              - { label: "Caption", name: "caption", widget: "string", required: false }
      - label: "Brochure"
        name: "brochure"
        widget: "object"
        collapsed: true
        fields:
          - { label: "Background Image", name: "background", widget: "image", required: false, choose_url: false, hint: "Dimensions: 1200 x 400 pixels" }
          - { label: "PDF File", name: "pdf", widget: "file", required: false, choose_url: false }
      - label: "Location"
        name: "location"
        widget: "object"
        collapsed: true
        fields:
          - { label: "Heading", name: "heading", widget: "string", required: false }
          - { label: "Sub Heading", name: "sub-heading", widget: "string", required: false }
          - { label: "Map Link", name: "map-link", widget: "string", required: false, hint: 'From Google Maps Eg: https://maps.app.goo.gl/PfUwVyD8C2xvM2GX7' }
          - { label: "Map Embed", name: "map-embed", widget: "string", required: false, hint: 'Note: Remove height, width and style attributes. Eg: <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1594.8431091199511!2d77.73660262614308!3d12.977434744615737!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bae11f093ce84ed%3A0x181d9c5cb50023cf!2sVaswani%20Starlight!5e0!3m2!1sen!2sin!4v1755611327119!5m2!1sen!2sin" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>' }
          - label: "Places Nearby"
            name: "places"
            widget: "list"
            required: false
            minimize_collapsed: true
            summary: '{{fields.name}}'
            fields:
              - { label: "Place Group Name", name: "name", widget: "string", required: false, hint: "Eg: Schools" }
              - label: "Place"
                name: "place"
                widget: "list"
                required: false
                minimize_collapsed: true
                summary: '{{fields.name}} {{fields.distance}}'
                fields:
                  - { label: Place Name, name: name, widget: string, required: false, hint: "Eg: Mallya Aditi International School" }
                  - { label: Distance, name: distance, widget: string, required: false, hint: "Eg: 4.0 Km" }
      - label: "Progress"
        name: "progress"
        widget: "object"
        collapsed: true
        fields:
          - { label: "Heading", name: "heading", widget: "string", required: false }
          - { label: "Sub Heading", name: "sub-heading", widget: "string", required: false }
          - label: "Entry"
            name: "entry"
            widget: "list"
            required: false
            minimize_collapsed: true
            summary: '{{fields.title}}'
            fields:
              - { label: Title, name: title, widget: string, required: false, hint: "Eg: Feb 2025" }
              - { label: "Heading", name: "heading", widget: "string", required: false }
              - { label: "Description", name: "description", widget: "text", required: false }
              - label: "Gallery"
                name: "gallery"
                widget: "list"
                required: false
                minimize_collapsed: true
                summary: '{{fields.image}} {{fields.caption}}'
                fields:
                  - { label: "Image", name: "image", widget: "image", choose_url: false }
                  - { label: "Caption", name: "caption", widget: "string", required: false }
      - label: "Banner"
        name: "banner"
        widget: "object"
        collapsed: true
        fields:
          - label: "Feature 1"
            name: "feature-1"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Heading", name: "heading", widget: "string", required: false }
              - label: "Align Text"
                name: "align-text"
                widget: "select"
                multiple: false
                options:
                  - { label: "Left", value: "left" }
                  - { label: "Right", value: "right" }
                  - { label: "Center", value: "center" }
                default: "left"
                required: false
              - label: "Position Text"
                name: "position-text"
                widget: "select"
                multiple: false
                options:
                  - { label: "Top", value: "top" }
                  - { label: "Bottom", value: "bottom" }
                  - { label: "Center", value: "center" }
                default: "top"
                required: false
              - { label: "Background", name: "background", widget: "image", choose_url: false, required: false }
              - label: "Background Fix"
                name: "background-fix"
                widget: "select"
                multiple: false
                options:
                  - { label: "Left Top", value: "left top" }
                  - { label: "Center Top", value: "center top" }
                  - { label: "Right Top", value: "right top" }
                  - { label: "Left Center", value: "left center" }
                  - { label: "Center Center", value: "center center" }
                  - { label: "Right Center", value: "right center" }
                  - { label: "Left Bottom", value: "left bottom" }
                  - { label: "Center Bottom", value: "center bottom" }
                  - { label: "Right Bottom", value: "right bottom" }
                default: "center center"
                required: false
                hint: "Value 1 = Horizontal, Value 2 = Vertical"
          - label: "Feature 2"
            name: "feature-2"
            widget: "object"
            collapsed: true
            fields:
              - { label: "Heading", name: "heading", widget: "string", required: false }
              - label: "Align Text"
                name: "align-text"
                widget: "select"
                multiple: false
                options:
                  - { label: "Left", value: "left" }
                  - { label: "Right", value: "right" }
                  - { label: "Center", value: "center" }
                default: "left"
                required: false
              - label: "Position Text"
                name: "position-text"
                widget: "select"
                multiple: false
                options:
                  - { label: "Top", value: "top" }
                  - { label: "Bottom", value: "bottom" }
                  - { label: "Center", value: "center" }
                default: "top"
                required: false
              - { label: "Background", name: "background", widget: "image", choose_url: false, required: false }
              - label: "Background Fix"
                name: "background-fix"
                widget: "select"
                multiple: false
                options:
                  - { label: "Left Top", value: "left top" }
                  - { label: "Center Top", value: "center top" }
                  - { label: "Right Top", value: "right top" }
                  - { label: "Left Center", value: "left center" }
                  - { label: "Center Center", value: "center center" }
                  - { label: "Right Center", value: "right center" }
                  - { label: "Left Bottom", value: "left bottom" }
                  - { label: "Center Bottom", value: "center bottom" }
                  - { label: "Right Bottom", value: "right bottom" }
                default: "center center"
                required: false
                hint: "Value 1 = Horizontal, Value 2 = Vertical"
  - name: "articles"
    label: "Articles"
    folder: "articles"
    icon: newsmode
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    sortable_fields: ['date', 'title']
    fields:
      - { label: "Tags", name: "tags", widget: "hidden", default: ["articles"] }
      - { label: "Created Date", name: "date", widget: "datetime", default: "{{now}}" }
      - { label: "Title", name: "title", widget: "string", hint: "Limit to 45 Characters" }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Cover Image", name: "cover", widget: "image", hint: "Aspect Ratio 2:1 (Width = 2 x Height)", required: false }
      - { label: "SEO Short Description", name: "description", widget: "text", hint: "Limit to 150 Characters", required: false }
      - label: "Author Credit"
        name: "author-credit"
        widget: "object"
        collapsed: true
        required: false
        fields:
          - { label: "Author Name", name: "name", widget: "string", hint: "Eg: Hima Nair", required: false }
          - { label: "Author Title", name: "title", widget: "string", hint: "Eg: Speech Language Pathologist", required: false }
          - { label: "Author Website URL (Optional)", name: "website", hint: "Eg: `https://bambinotherapy.com` — Note: Add Full URL including https", widget: "string", required: false }
          - { label: "Article Source Backlink (Optional)", name: "backlink", widget: "string", hint: "Eg: `https://bambinotherapy.com/articles/sample-article`", required: false }
          - { label: "Author Photo", name: "photo", widget: "image", hint: "Aspect Ratio 1:1 (Square Image)", required: false }
  - name: "testimonials"
    label: "Testimonials"
    folder: "testimonials"
    icon: reviews
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    sortable_fields: ['date', 'title']
    fields:
      - { label: "Tags", name: "tags", widget: "hidden", default: ["testimonials"] }
      - { label: "Created Date", name: "date", widget: "datetime", default: "{{now}}" }
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Rating", name: "rating", widget: "number", min: 0, max: 5, value_type: "int" }
      - { label: "Content", name: "content", widget: "text" }
  - name: "settings"
    label: "Settings"
    icon: settings
    editor:
      preview: false
    files:
      - name: "menu"
        label: "Menu"
        file: "_data/menu.json"
        fields:
          - label: "link"
            name: "link"
            widget: "list"
            summary: '{{fields.title}} → {{fields.path}}'
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Path", name: "path", widget: "string" }


